export const SUPORTED_LANGUAGES = {
    en: 'Inglés',
    es: 'Español',
    fr: 'Francés',
    de: 'Alemán',
    it: 'Italiano',
    nl: 'Neerlandés',
    pl: 'Polaco',
    pt: 'Portugués',
    ru: 'Ruso',
    ja: 'Japonés',
    zh: 'Chino',
    ar: 'Árabe',
    tr: 'Turco',
    uk: 'Ucraniano',
    ro: 'Rumano',
    nb: 'Noruego',
    lv: 'Letón',
    lt: 'Lituano',
    ko: 'Coreano',
    id: 'Indonesio',
    hu: 'Húngaro',
    fi: 'Finlandés',
    et: 'Estonio',
    el: 'Griego',
    da: 'Danés',
    cs: 'Checo',
    bg: 'Búlgaro',
};

export const AUTO_LANGUAGE = 'auto';
